
const pinkHeartUrl = '/images/pinkHeart.gif'
const purpleHeartUrl = '/images/purpleHeart.gif'
const pinkSparkleUrl = '/images/pinkSparkle.gif'
export const pinkSkullUrl = '/images/pinkSkull.gif'
export const starsUrl = '/images/stars.gif'
export const leavesUrl = '/images/leaves.gif'
export const imageType = 'image'
export const colorType = 'color'
export const bothType = 'both'
